CREATE TABLE IF NOT EXISTS profiles(
    id BIGSERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS talks(
    id BIGSERIAL PRIMARY KEY,
    speaker_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_talks_speaker_id__id FOREIGN KEY(speaker_id) REFERENCES profiles(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE SEQUENCE IF NOT EXISTS talks_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
